import "@styles/globals.css";
import { Toaster, toast } from "sonner";
import { config, icon } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import ThemeProvider from "@components/theme/ThemeProvider";
import SideBar from "@components/UI/Layout/SideBar";
import { DashboardRoutes } from "@constant/DashboardRoute";
config.autoAddCss = false;

export const metadata = {
  title: "Electro Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <SideBar menu={DashboardRoutes}>{children}</SideBar>
      </body>
    </html>
  );
}
