import "@styles/globals.css";
import { Toaster, toast } from "sonner";
import Nav from "@components/UI/Nav";
import Footer from "@components/UI/Footer";
import { config, icon } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import SupportChatBox from "@components/Chat/SupportChatBox";
import ThemeProvider from "@components/theme/ThemeProvider";
import Providers from "@provider/ReduxProvider";
import useSyncSession from "@provider/redux/useSyncSession";

config.autoAddCss = false;

export const metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
  icons: {
    icon: process.env.NEXT_PUBLIC_APP_LOGO, // Ensure this path is correct
  },
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <Providers>
            {" "}
            {/* Wrap with Providers */}
            <div className="min-h-[100vh] flex flex-col background">
              <Nav />
              <div className="grow h-fit flex justify-center">
                <div className="max-w-[1200px] w-full px-2 py-4">
                  {children}
                </div>
              </div>
              <Footer />
              <SupportChatBox />
            </div>
            <Toaster richColors position="bottom-right" />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
