import "@styles/globals.css";
import { Toaster, toast } from "sonner";
import { config, icon } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import ThemeProvider from "@components/theme/ThemeProvider";
import SideBar from "@components/UI/Layout/SideBar";
import { DashboardRoutes } from "@constant/DashboardRoute";
import Provider from "@provider/Provider";
config.autoAddCss = false;

export const metadata = {
  title: "Electro Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: process.env.NEXT_PUBLIC_APP_LOGO, // Ensure this path is correct
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ThemeProvider>
          <Provider>
            <div className="min-h-[100vh] flex flex-col background">
              {children}
            </div>
            <Toaster richColors position="bottom-right" />
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
