const SOCKET_JOIN_CHANNEL = {
  STAFF_JOIN: "STAFF_JOIN",
  STAFF_LEAVE: "STAFF_LEAVE",

  CUSTOMER_JOIN: "CUSTOMER_JOIN",
  CUSTOMER_LEAVE: "CUSTOMER_LEAVE",
};

const SOCKET_INBOX_CHANNEL = {
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",

  GET_MORE_MESSAGES: "GET_MORE_MESSAGES",
  ADD_MESSAGE: "ADD_MESSAGE",
  GET_MESSAGES: "GET_MESSAGES",

  SEEN_MESSAGE: "SEEN_MESSAGE",
  // DELETE_MESSAGE: "DELETE_MESSAGE",

  GET_MORE_CONVERSATIONS: "GET_MORE_CONVERSATIONS",
  GET_CONVERSATIONS: "GET_CONVERSATIONS",
  // DELETE_CONVERSATION: "DELETE_CONVERSATION",
};


const SOCKET_NOTIFICATION_CHANNEL = {
  GET_NOTIFICATIONS: "GET_NOTIFICATION",
  // GET_MORE_NOTIFICATIONS: "GET_MORE_NOTIFICATIONS",

  // READ_NOTIFICATION: "READ_NOTIFICATION",
  ADD_NOTIFICATIONS: "ADD_NOTIFICATION",
  // DELETE_NOTIFICATION: "DELETE_NOTIFICATION",
  // CLEAR_NOTIFICATION: "CLEAR_NOTIFICATION",
};

module.exports = {SOCKET_JOIN_CHANNEL,SOCKET_INBOX_CHANNEL,SOCKET_NOTIFICATION_CHANNEL}